@domain = http://localhost:3000
### Exibir ola chico



GET {{domain}}/

### Exibir Usuários

GET {{domain}}/rota

###


GET {{domain}}/users

###

POST {{domain}}/users

###

DELETE {{domain}}/users/40

### Exibir Programas

GET {{domain}}/programas

### Criar nova Semana

POST {{domain}}/programas

### Exibir Semana

GET {{domain}}/useres

###

POST {{domain}}/useres

###

GET {{domain}}/users/ref?id=1

###

POST {{domain}}/semana

###

POST {{domain}}/users/true

###

GET {{domain}}/users/true



