@domain = http://localhost:3000
@userId = {{signin.response.body.$.userId}}
@token = {{signin.response.body.$.token}}

### Exibir ola chico

### Create User
 
# @name createdUser
POST {{domain}}/users/true
Content-Type: application/json
 
{
  "name": "pablo",
  "email": "pablo.gay@gmail.com",
  "password": "12345678"
}

### Signin 401

# @name signin
POST {{domain}}/signin
Content-Type: application/json
 
{
  "email": "brabaohaikal@gmail.com",
  "password": "18"
}

### Signin Ok

# @name signin
POST {{domain}}/signin
Content-Type: application/json
 
{
  "email": "pablo.gay@gmail.com",
  "password": "12345678"
}

### Read User (with token)
 
GET {{domain}}/users/refe/{{userId}}
Authorization: bearer {{token}}

###

GET {{domain}}/users/refe/{{userId}}

###

GET {{domain}}/

### Exibir Usuários

GET {{domain}}/users/trues/{{userId}}
Authorization: bearer {{token}}


###


GET {{domain}}/users

###

POST {{domain}}/users

###

DELETE {{domain}}/users/40

### Exibir Programas

GET {{domain}}/programas

### Criar nova Semana

POST {{domain}}/programas

### Exibir Semana

GET {{domain}}/useres

###

POST {{domain}}/useres

###

GET {{domain}}/users/ref?id=1

###

POST {{domain}}/semana

###

POST {{domain}}/users/true

###

GET {{domain}}/users/true



