@domain = http://localhost:3000

### Exibir ola chico

GET {{domain}}/

### Exibir Usuários

GET {{domain}}/rota

###
GET {{domain}}/users

###

POST {{domain}}/users

### Exibir Programas

GET {{domain}}/programas

### Criar nova Semana

POST {{domain}}/programas

